name: Bart van Zon
author: Bart van Zon
description: The rants of a software developer
meta_description: "Bart van Zon's personal blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://bartvanzon.com'
google_analytics: 'UA-31563534-1'
permalink: /blog/:year/:month/:day/:title/
gems:
  - jekyll-sitemap
  - jekyll-feed
