name: Bart van Zon
description: The rants of a software developer
meta_description: "Bart van Zon's personal blog"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.bartvanzon.com'
google_analytics: 'UA-31563534-1'
permalink: '/:year/:month/:day/:title.html'

# Details for the RSS feed generator
url:            'http://www.bartvanzon.com'
author:         'Bart van Zon'
